image: cytopia/ansible:latest

stages:
  - connection_test
  - build
  - test
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

before_script:
  - export ANSIBLE_CONFIG=$CI_PROJECT_DIR/ansible.cfg
  - pip install paramiko

connection_test:
  stage: connection_test
  script:
    - echo "Testing SSH connectivity to all routers"
    - ansible all -i inventory.yml -m ping

build:
  stage: build
  script:
    - echo "Configuring OSPF for R1 and R2"
    - ansible-playbook configure_ospf.yml -i inventory.yml --limit R1,R2

test:
  stage: test
  script:
    - echo "Verifying OSPF Neighborship between R1 and R2"
    - ansible-playbook verify_ospf.yml -i inventory.yml --limit R1,R2

deploy:
  stage: deploy
  script:
    - echo "Configuring OSPF for R2 and R3"
    - ansible-playbook configure_ospf.yml -i inventory.yml --limit R2,R3

    - echo "Verifying OSPF Neighborship between R2 and R3"
    - ansible-playbook verify_ospf.yml -i inventory.yml --limit R2,R3
