image: python:3.10-slim

stages:
  - connection_test
  - build
  - test
  - deploy

variables:
  ANSIBLE_HOST_KEY_CHECKING: "False"

before_script:
  # Update system and install required dependencies
  - apt-get update && apt-get install -y sshpass git libffi-dev gcc
  # Create and activate a virtual environment
  - python3 -m venv .venv
  - source .venv/bin/activate
  # Upgrade pip and install required Python packages
  - pip install --upgrade pip
  - pip install ansible ansible-pylibssh jinja2 paramiko pyyaml
  # Ensure correct directory permissions
  - chmod 755 $CI_PROJECT_DIR

connection_test:
  stage: connection_test
  script:
    - echo "Testing SSH connectivity to all routers"
    - ansible all -i inventory.yml -m ping

build:
  stage: build
  script:
    - echo "Verifying SSH access with CLI commands"
    - ansible-playbook verify_ssh.yml -i inventory.yml -vvv
    - echo "Configuring OSPF for R1 and R2"
    - ansible-playbook configure_ospf.yml -i inventory.yml -vvv

test:
  stage: test
  script:
    - echo "Verifying OSPF Neighborship between R1 and R2"
    - ansible-playbook verify_ospf.yml -i inventory.yml 

