---
- name: Configure OSPF
  hosts: all
  gather_facts: no
  tasks:
    - name: Debug connection details
      debug:
        msg: "Connecting to {{ inventory_hostname }} ({{ ansible_host }}) with router ID {{ router_id }}"

    - name: Configure OSPF on the router
      ios_config:
        lines:
          - "no router ospf 1"
          - "router ospf 1"
          - "router-id {{ router_id }}"
          - "network 0.0.0.0 0.0.0.0 area 0"
