---
- name: Verify SSH Access with CLI Commands
  hosts: all
  gather_facts: no
  tasks:
    - name: Run 'show version' on all devices
      ansible.netcommon.cli_command:
        command: show version
      register: version_output

    - name: Display output
      debug:
        msg: "{{ version_output.stdout_lines }}"
